apiVersion: v1
kind: Pod
metadata:
  name: emitter
  labels:
    name: emitter
spec:
  containers:
  - name: emitter
    image: logk8s/emmiter
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - name: http
        protocol: TCP
        containerPort: 3010